### ISSUE TITLE
打包zerotier

### ISSUE THREAD

**Issue by cyh230** [igithublab/MT1300#1]
用了你的软件包，使用很好，全协议支持。另外，大神能不能把zerotier软件也编译到软件包里，谢谢😜

**Comment by igithublab** [comment]
你可以尝试fork一下，然后修改 .config.gl 配置文件，将以下包编译到固件里。
我发现最近GL-iNet已经将MT1300提交到官方源码了，而且Lean大神已经进行了适配。
我正在尝试从Lean编译，不知道能否搞定WIFI，Lean的源码好像有MT7615的闭源WIFI驱动，应该可以搞定。
而官方源码要添加闭源驱动，还需要改内核到5.4.x才行，这个我还不太懂。

CONFIG_PACKAGE_libstdcpp=y
CONFIG_PACKAGE_kmod-tun=y
CONFIG_PACKAGE_libminiupnpc=y
CONFIG_PACKAGE_libnatpmp=y
CONFIG_PACKAGE_luci-app-zerotier=y
CONFIG_PACKAGE_luci-i18n-zerotier-zh-cn=y
CONFIG_PACKAGE_zerotier=y

**Comment by cyh230** [comment]
用lean的源码编译zerotier包有问题，装到mt1300里，zerotier配置好一启动，整个系统就崩溃了，拿不到ip地址，重启也不行，只能重刷官方固件了。
我小小白一个，一块折腾吧😄
