### ISSUE TITLE
老大，除了最早版本的插件包可以自动安装成功，后面几个版本都安装失败。

### ISSUE THREAD

**Issue by andyhe80** [igithublab/MT1300#2]
显示缺trojan，Xray 安装包，和shadowsocks-libev-ss-local 和shadowsocks-libev-ss-redir依赖

**Comment by Harris-Shelby** [comment]
最早版本的ipk还有吗，可以分享一下吗

**Comment by igithublab** [comment]
我也不是什么编译大佬，只是买了这个设备，为了自己出差方便使用而已。最早想用gl的源码编译出自己的openwrt，结果他们的源码一堆堆问题，DHCP无法获取IP地址这个是很头痛的事情。所以才想到用他们的源码编译插件，然后用他们官方的固件，安装插件来使用。
目前我已经采用了lienol的源码编译，采用单路WIFI，稳定使用一段时间了，所以gl的源码的所有编译都不想折腾了。毕竟我主要出差工作使用，没有多余的路由器折腾。

**Comment by andyhe80** [comment]
> 最早版本的ipk还有吗，可以分享一下吗

https://github.com/Chikage/GL.iNET-MT1300    你干脆刷这个版本，除了不能无线中继，其他完美，每天自动更新

**Comment by Harris-Shelby** [comment]
谢谢了，我主要买这个路由器也是为了出差时用的，官方的固件包界面啥的还是挺好看的，我还是用官方的固件包吧。
我已经找到原因了，谢谢了。

**Comment by andyhe80** [comment]
> 谢谢了，我主要买这个路由器也是为了出差时用的，官方的固件包界面啥的还是挺好看的，我还是用官方的固件包吧。
> 我已经找到原因了，谢谢了。

什么原因？能分享下吗
