### ISSUE TITLE
插件无法安装使用

### ISSUE THREAD

**Issue by Harris-Shelby** [igithublab/MT1300#3]
大佬，OpenWrt_firmware_gl-mt1300_yyyymmddhhmm 中的酸酸乳插件没法安装，可以修复吗

**Comment by igithublab** [comment]
我也不是什么编译大佬，只是买了这个设备，为了自己出差方便使用而已。最早想用gl的源码编译出自己的openwrt，结果他们的源码一堆堆问题，DHCP无法获取IP地址这个是很头痛的事情。所以才想到用他们的源码编译插件，然后用他们官方的固件，安装插件来使用。
目前我已经采用了lienol的源码编译，采用单路WIFI，稳定使用一段时间了，所以gl的源码的所有编译都不想折腾了。毕竟我主要出差工作使用，没有多余的路由器折腾。
